# Generated by Django 5.1.2 on 2025-01-22 09:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("main_paciente", "0005_add_property_igc_atual"),
    ]

    operations = [
        migrations.CreateModel(
            name="Npt",
            fields=[
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("inicio", models.DateField(auto_now_add=True)),
                ("fim", models.DateField(auto_now=True)),
                (
                    "cod_pac",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="npt",
                        to="main_paciente.paciente",
                    ),
                ),
            ],
            options={
                "ordering": ("-inicio",),
            },
        ),
    ]
