# Generated by Django 5.1.2 on 2025-01-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_npt", "0001_add_npt_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="npt",
            name="fim",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="npt",
            name="inicio",
            field=models.DateField(),
        ),
    ]
