# Generated by Django 5.1.2 on 2024-11-18 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_leito", "0001_alter_model_add_cod_leito"),
        ("main_paciente", "0001_add_paciente_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="cod_leito",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="pacientes",
                to="main_leito.leito",
            ),
        ),
    ]
