# Generated by Django 5.1.2 on 2024-11-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_paciente", "0003_alter_model_add_field_added_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
