# Generated by Django 5.1.2 on 2024-12-23 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_paciente", "0004_alter_model_add_created_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paciente",
            options={"ordering": ["-created_at"]},
        ),
    ]
