# Generated by Django 5.1.2 on 2024-10-23 23:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("main_hospital", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medico",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("crm", models.CharField(db_index=True, max_length=255, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "hospitais",
                    models.ManyToManyField(
                        related_name="medicos", to="main_hospital.hospital"
                    ),
                ),
            ],
            options={
                "verbose_name": "medico",
                "verbose_name_plural": "medicos",
            },
            bases=("auth.user",),
        ),
    ]
