# Generated by Django 5.1.2 on 2024-11-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_medico", "0002_alter_model_groups_permissions_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medico",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
