# Generated by Django 5.1.1 on 2024-10-15 20:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("main_hospital", "0002_alter_model_add_sigla"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=250)),
                ("nasc", models.DateField()),
                ("p_nasc", models.IntegerField()),
                ("ig_nasc", models.IntegerField()),
                (
                    "cod_hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_hospital.hospitalmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
