# Generated by Django 5.1.2 on 2024-11-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_hospital", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
