# Generated by Django 5.1.1 on 2024-10-16 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_hospital", "0002_alter_model_add_sigla"),
        ("main_patient", "0001_add_patient_model"),
        ("main_user", "0004_alter_model_add_hospitais"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HospitalModel",
            new_name="Hospital",
        ),
        migrations.AlterModelOptions(
            name="hospital",
            options={"verbose_name": "Hospital", "verbose_name_plural": "Hospitais"},
        ),
    ]
