# Generated by Django 5.1.1 on 2024-10-03 08:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_user", "0001_inicial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Medico",
            new_name="MedicoModel",
        ),
    ]
