# Generated by Django 5.1.1 on 2024-10-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_hospital", "0001_inicial"),
        ("main_user", "0003_alter_hospitalmodel_add_medicos_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicomodel",
            name="hospitais",
            field=models.ManyToManyField(
                related_name="medicos", to="main_hospital.hospitalmodel"
            ),
        ),
    ]
