# Generated by Django 5.1.1 on 2024-10-16 20:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_hospital", "0003_alter_nome_models"),
        ("main_user", "0004_alter_model_add_hospitais"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MedicoModel",
            new_name="Medico",
        ),
    ]
