# Generated by Django 5.1.2 on 2025-03-02 19:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("main_npt", "0004_alter_model_fim_nulltrue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescricao",
            fields=[
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("peso", models.DecimalField(decimal_places=1, max_digits=5)),
                ("volume", models.DecimalField(decimal_places=1, max_digits=4)),
                ("vig", models.DecimalField(decimal_places=1, max_digits=2)),
                ("aac", models.DecimalField(decimal_places=1, max_digits=2)),
                ("lip", models.DecimalField(decimal_places=1, max_digits=2)),
                ("ca", models.DecimalField(decimal_places=1, max_digits=2)),
                ("na", models.DecimalField(decimal_places=1, max_digits=2)),
                ("k", models.DecimalField(decimal_places=1, max_digits=2)),
                ("p", models.DecimalField(decimal_places=1, max_digits=2)),
                ("mg", models.DecimalField(decimal_places=1, max_digits=2)),
                ("oligo", models.DecimalField(decimal_places=1, max_digits=2)),
                ("vit", models.DecimalField(decimal_places=1, max_digits=2)),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "cod_medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="prescricao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cod_npt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="prescricao",
                        to="main_npt.npt",
                    ),
                ),
            ],
            options={
                "ordering": ("-data",),
            },
        ),
    ]
